#!/usr/bin/env bash
# Build / serve script with three modes:
#   mock    - Mock auth (USE_MOCK=true), watch + dev server
#   dev     - Real auth (Kratos+Hydra), watch + dev server, COOKIE_SECRET persisted in scripts/.env.dev
#   release - Real auth, optimized production bundle via purs-backend-es + minify. Build only (no server).
#
# Usage: ./scripts/dev.sh [mock|dev|release]   (default: mock)

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ $# -gt 1 ]]; then
  echo "Usage: $0 [mock|dev|release]" >&2
  exit 1
fi

MODE="${1:-mock}"

case "$MODE" in
  mock|dev|release) ;;
  *)
    echo "Usage: $0 [mock|dev|release]" >&2
    echo "  mock    - Mock auth, watch + dev server (default)" >&2
    echo "  dev     - Real auth (Kratos+Hydra), watch + dev server" >&2
    echo "  release - Real auth, optimized production bundle (build only)" >&2
    exit 1
    ;;
esac

ENV_FILE="scripts/.env.dev"

bundle_dev() {
  spago bundle --platform browser --module Client --outfile dist/app.js
  spago bundle --platform node --module Server --outfile dist/server.js --bundle-type module
}

bundle_release() {
  echo "==> Building (corefn for purs-backend-es)..."
  spago build

  echo "==> Optimizing with purs-backend-es..."
  purs-backend-es build

  echo "==> Bundling client (esbuild minify)..."
  purs-backend-es bundle-app \
    --no-build \
    --main Client \
    --platform browser \
    --to dist/app.js
  # purs-backend-es emits an ES module; run a final minify pass with esbuild
  esbuild dist/app.js --bundle --format=esm --minify --legal-comments=none --outfile=dist/app.js --allow-overwrite

  echo "==> Bundling server (esbuild minify)..."
  purs-backend-es bundle-module \
    --no-build \
    --main Server \
    --platform node \
    --to dist/server.js
  esbuild dist/server.js --bundle --format=esm --platform=node --minify --legal-comments=none --outfile=dist/server.js --allow-overwrite
}

bundle_css() {
  local extra=()
  if [[ "$MODE" == "release" ]]; then
    extra+=(--minify)
  fi
  bunx @tailwindcss/cli -i src/style.css -o dist/style.css "${extra[@]}"
}

# COOKIE_SECRET_BASE64 only needs to be visible to `bun index.ts`. We intentionally
# avoid `set -a` / blanket export so watchexec / spago / tailwind subprocesses do
# not inherit the secret into their environment.
COOKIE_SECRET_FOR_BUN=""

case "$MODE" in
  mock)
    export USE_MOCK=true
    ;;

  dev)
    export USE_MOCK=false
    # Persist COOKIE_SECRET across restarts so sessions/OAuth-state cookies survive.
    # Generate inside a subshell so umask 077 does not leak to the rest of the script.
    if [[ ! -f "$ENV_FILE" ]]; then
      mkdir -p "$(dirname "$ENV_FILE")"
      (
        umask 077
        {
          echo "# Auto-generated by scripts/dev.sh (dev mode). Do not commit."
          echo "COOKIE_SECRET_BASE64=$(openssl rand -base64 32)"
        } > "$ENV_FILE"
      )
      echo "==> Generated $ENV_FILE"
    fi
    # Parse the value without exporting it globally.
    # `|| true` keeps grep's "no match" non-zero exit from tripping `set -e`,
    # so a malformed/empty $ENV_FILE reaches the user-facing error below.
    COOKIE_SECRET_FOR_BUN="$(grep -E '^COOKIE_SECRET_BASE64=' "$ENV_FILE" | head -n1 | cut -d= -f2- || true)"
    if [[ -z "$COOKIE_SECRET_FOR_BUN" ]]; then
      echo "ERROR: COOKIE_SECRET_BASE64 not found in $ENV_FILE." >&2
      echo "Delete the file and re-run to regenerate." >&2
      exit 1
    fi
    ;;

  release)
    export USE_MOCK=false
    # Release builds embed nothing secret, but we require the variable at build
    # time so the operator confirms they have a secret ready for the artifact.
    if [[ -z "${COOKIE_SECRET_BASE64:-}" ]]; then
      echo "ERROR: COOKIE_SECRET_BASE64 must be set in the environment for release builds." >&2
      echo "Generate one with:  openssl rand -base64 32" >&2
      exit 1
    fi
    ;;
esac

# release: build artifacts only, then exit
if [[ "$MODE" == "release" ]]; then
  bundle_release
  bundle_css
  echo "==> Release build complete. Artifacts in dist/. Start with: bun index.ts"
  exit 0
fi

# Track only the PIDs we launch so cleanup doesn't kill sibling processes
# (e.g. when run under a wrapping process manager).
CHILD_PIDS=()

cleanup() {
  for pid in "${CHILD_PIDS[@]}"; do
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
}
trap cleanup EXIT INT TERM

bundle_dev
bundle_css

# --postpone: do not run the command at startup; we already did the initial bundle above.
# Watch both .purs sources and spago.yaml / spago.lock so dependency changes trigger rebundle.
watchexec \
  --postpone \
  -w src -w spago.yaml -w spago.lock \
  --filter '*.purs' --filter spago.yaml --filter spago.lock \
  -- \
  "spago bundle --platform browser --module Client --outfile dist/app.js && \
   spago bundle --platform node --module Server --outfile dist/server.js --bundle-type module" &
CHILD_PIDS+=($!)

bunx @tailwindcss/cli -i src/style.css -o dist/style.css --watch=always &
CHILD_PIDS+=($!)

# Only `bun index.ts` receives COOKIE_SECRET_BASE64. The watch + tailwind processes
# above were spawned before this export so they don't inherit the secret.
if [[ -n "$COOKIE_SECRET_FOR_BUN" ]]; then
  COOKIE_SECRET_BASE64="$COOKIE_SECRET_FOR_BUN" bun index.ts &
else
  bun index.ts &
fi
BUN_PID=$!
CHILD_PIDS+=("$BUN_PID")

# Wait for any child to exit. If one dies (e.g. bun crashes on port-in-use),
# we tear down the rest immediately rather than appearing to hang.
wait -n
EXIT_CODE=$?
cleanup
exit "$EXIT_CODE"
