#!/usr/bin/env bash
# Build / serve script with three modes:
#   mock    - Mock auth (USE_MOCK=true), watch + dev server
#   dev     - Real auth (Kratos+Hydra), watch + dev server, COOKIE_SECRET persisted in scripts/.env.dev
#   release - Real auth, optimized production bundle via purs-backend-es + minify. Build only (no server).
#
# Usage: ./scripts/dev.sh [mock|dev|release]   (default: mock)

set -euo pipefail

cd "$(dirname "$0")/.."

MODE="${1:-mock}"

case "$MODE" in
  mock|dev|release) ;;
  *)
    echo "Usage: $0 [mock|dev|release]" >&2
    echo "  mock    - Mock auth, watch + dev server (default)" >&2
    echo "  dev     - Real auth (Kratos+Hydra), watch + dev server" >&2
    echo "  release - Real auth, optimized production bundle (build only)" >&2
    exit 1
    ;;
esac

ENV_FILE="scripts/.env.dev"

bundle_dev() {
  spago bundle --platform browser --module Client --outfile dist/app.js
  spago bundle --platform node --module Server --outfile dist/server.js --bundle-type module
}

bundle_release() {
  echo "==> Building (corefn for purs-backend-es)..."
  spago build

  echo "==> Optimizing with purs-backend-es..."
  purs-backend-es build

  echo "==> Bundling client (esbuild minify)..."
  purs-backend-es bundle-app \
    --no-build \
    --main Client \
    --platform browser \
    --to dist/app.js
  # purs-backend-es emits an ES module; run a final minify pass with esbuild
  esbuild dist/app.js --bundle --format=esm --minify --legal-comments=none --outfile=dist/app.js --allow-overwrite

  echo "==> Bundling server (esbuild minify)..."
  purs-backend-es bundle-module \
    --no-build \
    --main Server \
    --platform node \
    --to dist/server.js
  esbuild dist/server.js --bundle --format=esm --platform=node --minify --legal-comments=none --outfile=dist/server.js --allow-overwrite
}

bundle_css() {
  local extra=()
  if [[ "$MODE" == "release" ]]; then
    extra+=(--minify)
  fi
  bunx @tailwindcss/cli -i src/style.css -o dist/style.css "${extra[@]}"
}

case "$MODE" in
  mock)
    export USE_MOCK=true
    ;;

  dev)
    export USE_MOCK=false
    # Persist COOKIE_SECRET across restarts so sessions/OAuth-state cookies survive
    if [[ ! -f "$ENV_FILE" ]]; then
      mkdir -p "$(dirname "$ENV_FILE")"
      umask 077
      {
        echo "# Auto-generated by scripts/dev.sh (dev mode). Do not commit."
        echo "COOKIE_SECRET_BASE64=$(openssl rand -base64 32)"
      } > "$ENV_FILE"
      echo "==> Generated $ENV_FILE"
    fi
    # shellcheck source=/dev/null
    set -a
    source "$ENV_FILE"
    set +a
    ;;

  release)
    export USE_MOCK=false
    if [[ -z "${COOKIE_SECRET_BASE64:-}" ]]; then
      echo "ERROR: COOKIE_SECRET_BASE64 must be set in the environment for release builds." >&2
      echo "Generate one with:  openssl rand -base64 32" >&2
      exit 1
    fi
    ;;
esac

# release: build artifacts only, then exit
if [[ "$MODE" == "release" ]]; then
  bundle_release
  bundle_css
  echo "==> Release build complete. Artifacts in dist/. Start with: bun index.ts"
  exit 0
fi

cleanup() {
  kill 0 2>/dev/null || true
}
trap cleanup EXIT INT TERM

bundle_dev
bundle_css

watchexec -w src -w spago.yaml -e purs -- \
  "spago bundle --platform browser --module Client --outfile dist/app.js && \
   spago bundle --platform node --module Server --outfile dist/server.js --bundle-type module" &

bunx @tailwindcss/cli -i src/style.css -o dist/style.css --watch &

bun index.ts &

wait
